//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAsp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetAsp.Resources.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to list.
        /// </summary>
        public static string BackList {
            get {
                return ResourceManager.GetString("BackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Article.
        /// </summary>
        public static string ChoixArt {
            get {
                return ResourceManager.GetString("ChoixArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Categorie.
        /// </summary>
        public static string ChoixCat {
            get {
                return ResourceManager.GetString("ChoixCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Languages.
        /// </summary>
        public static string ChooseLang {
            get {
                return ResourceManager.GetString("ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Article.
        /// </summary>
        public static string CreateArt {
            get {
                return ResourceManager.GetString("CreateArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create categorie.
        /// </summary>
        public static string CreateCat {
            get {
                return ResourceManager.GetString("CreateCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earning By Articles.
        /// </summary>
        public static string EarningByArticles {
            get {
                return ResourceManager.GetString("EarningByArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Article.
        /// </summary>
        public static string EditArt {
            get {
                return ResourceManager.GetString("EditArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Categorie.
        /// </summary>
        public static string EditCat {
            get {
                return ResourceManager.GetString("EditCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Customer.
        /// </summary>
        public static string EditClient {
            get {
                return ResourceManager.GetString("EditClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frensh.
        /// </summary>
        public static string Frensh {
            get {
                return ResourceManager.GetString("Frensh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article management.
        /// </summary>
        public static string GestionArticle {
            get {
                return ResourceManager.GetString("GestionArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie management.
        /// </summary>
        public static string GestionCategorie {
            get {
                return ResourceManager.GetString("GestionCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer management.
        /// </summary>
        public static string GestionClient {
            get {
                return ResourceManager.GetString("GestionClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Sold.
        /// </summary>
        public static string ItemsSold {
            get {
                return ResourceManager.GetString("ItemsSold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for datas &amp; reports.
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic.
        /// </summary>
        public static string Statistique {
            get {
                return ResourceManager.GetString("Statistique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic Page.
        /// </summary>
        public static string StatistiqueP {
            get {
                return ResourceManager.GetString("StatistiqueP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        public static string Thisweek {
            get {
                return ResourceManager.GetString("Thisweek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMBER OF ORDERS IN RELATIVE TO CATEGORIES.
        /// </summary>
        public static string TitireStatistique {
            get {
                return ResourceManager.GetString("TitireStatistique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMBER OF ORDERS IN RELATIVE TO PRODUCT.
        /// </summary>
        public static string TitireStatistiqueRound {
            get {
                return ResourceManager.GetString("TitireStatistiqueRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Articles.
        /// </summary>
        public static string TopArticles {
            get {
                return ResourceManager.GetString("TopArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Earnings.
        /// </summary>
        public static string totalEarnings {
            get {
                return ResourceManager.GetString("totalEarnings", resourceCulture);
            }
        }
    }
}
