//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAsp.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.Commandes = new HashSet<Commande>();
            this.Favoris = new HashSet<Favori>();
            this.Commentaires = new HashSet<Commentaire>();
        }
        public Article(int numArticle, string designation, double? prixU, int? stock, string photo, string statut, int? promo, string description, string detail, DateTime? datee, double? rating, string marque, int? vendu, int? refcat)
        {
            this.numArticle = numArticle;
            this.description = description;
            this.prixU = prixU;
            this.stock = stock;
            this.photo = photo;
            this.statut = statut;
            this.promo = promo;
            this.designation = designation;
            this.detail = detail;
            this.datee = datee;
            this.rating = rating;
            this.marque = marque;
            this.vendu = vendu;
            this.refcat = refcat;

        }

        public HttpPostedFileBase Imagefile { get; set; }

        public int numArticle { get; set; }
        public string designation { get; set; }
        public Nullable<double> prixU { get; set; }
        public Nullable<int> stock { get; set; }
        public string photo { get; set; }
        public string statut { get; set; }
        public Nullable<int> promo { get; set; }
        public string description { get; set; }
        public string detail { get; set; }
        public Nullable<System.DateTime> datee { get; set; }
        public Nullable<double> rating { get; set; }
        public string marque { get; set; }
        public Nullable<int> vendu { get; set; }
        public Nullable<int> refcat { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commande> Commandes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commentaire> Commentaires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favori> Favoris { get; set; }
    }
}
