//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAsp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.Commandes = new HashSet<Commande>();
            this.Favoris = new HashSet<Favori>();
            this.Commentaires = new HashSet<Commentaire>();
        }
    
        public int numArticle { get; set; }
       
        public string designation { get; set; }

        public Nullable<double> prixU { get; set; }

        public Nullable<int> stock { get; set; }

        public string photo { get; set; }

        public string statut { get; set; }

        public Nullable<int> promo { get; set; }

        public string description { get; set; }

        public string detail { get; set; }

        public Nullable<System.DateTime> datee { get; set; }

        public Nullable<double> rating { get; set; }

        public string marque { get; set; }

        public Nullable<int> vendu { get; set; }
        public Nullable<int> refcat { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commande> Commandes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favori> Favoris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commentaire> Commentaires { get; set; }

        public HttpPostedFileBase Imagefile { get; set; }

    }
}
