//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAsp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Commandes = new HashSet<Commande>();
            this.Favoris = new HashSet<Favori>();
        }
        public Client(int numClient, string login, string mdp, string nom, string prenom, string email, string ville, string tel, int role)
        {
            this.numClient = numClient;
            this.login = login;
            this.mdp = mdp;
            this.nom = nom;
            this.prenom = prenom;
            this.email = email;
            this.ville = ville;
            this.tel = tel;
            this.role = role;

            this.Commandes = new HashSet<Commande>();
            this.Favoris = new HashSet<Favori>();

        }
        public int numClient { get; set; }
        public string login { get; set; }
        public string mdp { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string email { get; set; }
        public string ville { get; set; }
        public string tel { get; set; }
        public Nullable<int> role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commande> Commandes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favori> Favoris { get; set; }
    }
}
