//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAsp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        public int numcmd { get; set; }
        public Nullable<System.DateTime> datecmd { get; set; }
        public Nullable<int> numclient { get; set; }
        public Nullable<int> numarticle { get; set; }
        public Nullable<int> qtearticle { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Client Client { get; set; }
    }
}
