//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAsp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentaire
    {
        public int idcom { get; set; }
        public string nomclient { get; set; }
        public string commentaire1 { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> numart { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
