//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAsp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        public int numcmd { get; set; }
        public Nullable<System.DateTime> datecmd { get; set; }
        public Nullable<int> numclient { get; set; }
        public Nullable<int> numarticle { get; set; }
        public Nullable<int> qtearticle { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Client Client { get; set; }
    }
}
