//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAsp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentaire
    {
        public int idcom { get; set; }
        public string nomclient { get; set; }
        public string commentaire1 { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> numart { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
